name: news_c17_st
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  google_fonts: ^6.3.2
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  loader_overlay: ^5.0.0
  cached_network_image: ^3.4.1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.5
  injectable: ^2.7.1+4
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.11.0
  injectable_generator: ^2.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/